name: Sync upstream

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git remote add upstream https://github.com/BAYUEQI/ZQ-Chat.git
          git fetch upstream
          git checkout main
          git merge --ff-only upstream/main || git merge upstream/main --no-edit
          git push origin main
